#############################################################################
# Makefile for building: MPDC
# Generated by qmake (2.01a) (Qt 4.4.0) on: ?? ?? 19 10:01:09 2014
# Project:  MPDC.pro
# Template: app
# Command: /home/uptech/QT4/for_arm/qt-embedded-linux-opensource-src-4.4.0/bin/qmake -unix -o Makefile MPDC.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/qws/linux-arm-g++ -I. -I/usr/local/Trolltech/Qt-embedded-4.4.0/include/QtCore -I/usr/local/Trolltech/Qt-embedded-4.4.0/include/QtCore -I/usr/local/Trolltech/Qt-embedded-4.4.0/include/QtNetwork -I/usr/local/Trolltech/Qt-embedded-4.4.0/include/QtNetwork -I/usr/local/Trolltech/Qt-embedded-4.4.0/include/QtGui -I/usr/local/Trolltech/Qt-embedded-4.4.0/include/QtGui -I/usr/local/Trolltech/Qt-embedded-4.4.0/include -I. -I. -I.
LINK          = arm-linux-g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-embedded-4.4.0/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-embedded-4.4.0/lib -lQtGui -L/home/uptech/QT4/for_arm/qt-embedded-linux-opensource-src-4.4.0/../tslib1.4-install/lib -L/usr/local/Trolltech/Qt-embedded-4.4.0/lib -lts -lQtNetwork -lQtCore -lz -lm -lrt -ldl -lpthread
AR            = arm-linux-ar cqs
RANLIB        = arm-linux-ranlib
QMAKE         = /home/uptech/QT4/for_arm/qt-embedded-linux-opensource-src-4.4.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = gps.c \
		main.cpp \
		mpdc.cpp \
		rgb2bmp.c \
		send_data.c \
		v4l.c moc_mpdc.cpp
OBJECTS       = gps.o \
		main.o \
		mpdc.o \
		rgb2bmp.o \
		send_data.o \
		v4l.o \
		moc_mpdc.o
DIST          = /usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/lex.prf \
		MPDC.pro
QMAKE_TARGET  = MPDC
DESTDIR       = 
TARGET        = MPDC

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mpdc.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MPDC.pro  /usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/qws/linux-arm-g++/qmake.conf /usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-embedded-4.4.0/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-embedded-4.4.0/lib/libQtNetwork.prl \
		/usr/local/Trolltech/Qt-embedded-4.4.0/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile MPDC.pro
/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-embedded-4.4.0/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-embedded-4.4.0/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-embedded-4.4.0/lib/libQtNetwork.prl:
/usr/local/Trolltech/Qt-embedded-4.4.0/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile MPDC.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/MPDC1.0.0 || $(MKDIR) .tmp/MPDC1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MPDC1.0.0/ && $(COPY_FILE) --parents gps.h mpdc.h pub.h rgb2bmp.h send_data.h v4l.h .tmp/MPDC1.0.0/ && $(COPY_FILE) --parents gps.c main.cpp mpdc.cpp rgb2bmp.c send_data.c v4l.c .tmp/MPDC1.0.0/ && $(COPY_FILE) --parents mpdc.ui .tmp/MPDC1.0.0/ && (cd `dirname .tmp/MPDC1.0.0` && $(TAR) MPDC1.0.0.tar MPDC1.0.0 && $(COMPRESS) MPDC1.0.0.tar) && $(MOVE) `dirname .tmp/MPDC1.0.0`/MPDC1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MPDC1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mpdc.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mpdc.cpp
moc_mpdc.cpp: ui_mpdc.h \
		v4l.h \
		pub.h \
		gps.h \
		mpdc.h
	/usr/local/Trolltech/Qt-embedded-4.4.0/bin/moc $(DEFINES) $(INCPATH) mpdc.h -o moc_mpdc.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mpdc.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mpdc.h
ui_mpdc.h: mpdc.ui
	/usr/local/Trolltech/Qt-embedded-4.4.0/bin/uic mpdc.ui -o ui_mpdc.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

gps.o: gps.c gps.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o gps.o gps.c

main.o: main.cpp mpdc.h \
		ui_mpdc.h \
		v4l.h \
		pub.h \
		gps.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mpdc.o: mpdc.cpp mpdc.h \
		ui_mpdc.h \
		v4l.h \
		pub.h \
		gps.h \
		rgb2bmp.h \
		send_data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpdc.o mpdc.cpp

rgb2bmp.o: rgb2bmp.c rgb2bmp.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o rgb2bmp.o rgb2bmp.c

send_data.o: send_data.c send_data.h \
		pub.h \
		gps.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o send_data.o send_data.c

v4l.o: v4l.c v4l.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o v4l.o v4l.c

moc_mpdc.o: moc_mpdc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mpdc.o moc_mpdc.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

