######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 19 10:01:05 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gps.h mpdc.h pub.h rgb2bmp.h send_data.h v4l.h
FORMS += mpdc.ui
SOURCES += gps.c main.cpp mpdc.cpp rgb2bmp.c send_data.c v4l.c
